In [47]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [81]:
V_shape = (5,5)
V = np.zeros(V_shape)
i_max = V.shape[0]-1
j_max = V.shape[1]-1
V

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [82]:
gamma = 0.9

In [83]:
def reward(i,j):
    if i==0 and j==0:
        return 0
    if i==i_max and j==j_max:
        return 0
    return -1

In [84]:
def next_states(i,j):
    states = []
    # left
    if j>0:
        states.append((i,j-1))
    # right
    if j<j_max:
        states.append((i,j+1))
    # up
    if i>0:
        states.append((i-1,j))
    # down
    if i<i_max:
        states.append((i+1,j))
    return states

In [85]:
# random policy
def next_V(V):
    V_prime = np.zeros(V_shape)
    for i in range(i_max+1):
        for j in range(j_max+1):
            states = next_states(i,j)
            p = 1/len(states)
            v_prime = 0
            for s in states:
                k,l = s
                r = reward(k,l)
                v_prime += p*(r + gamma*V[k,l])
            V_prime[i,j] = v_prime
    return V_prime

In [86]:
# greedy policy
def greedy_next_V(V):
    V_prime = np.zeros(V_shape)
    for i in range(i_max+1):
        for j in range(j_max+1):
            states = next_states(i,j)
            values_choice = []
            for s in states:
                k,l = s
                values_choice.append(V[k,l])
            arg_max = np.argmax(values_choice)
            k,l = states[arg_max]
            r = reward(k,l)
            V_prime[i,j] = (r + gamma*V[k,l])
    return V_prime

In [87]:
for _ in range(100):
    V = next_V(V)
V

array([[-9.02684442, -8.91874553, -9.27452777, -9.34705286],
       [-8.91874553, -9.20563115, -9.31604938, -9.27452777],
       [-9.27452777, -9.31604938, -9.20563115, -8.91874553],
       [-9.34705286, -9.27452777, -8.91874553, -9.02684442]])

In [88]:
for _ in range(100):
    V = next_V(V)
V

array([[-9.02708906, -8.91898784, -9.27477241, -9.34729517],
       [-8.91898784, -9.20587579, -9.31629169, -9.27477241],
       [-9.27477241, -9.31629169, -9.20587579, -8.91898784],
       [-9.34729517, -9.27477241, -8.91898784, -9.02708906]])

In [89]:
for _ in range(100):
    V = greedy_next_V(V)
V

array([[-5.26325787, -4.73695319, -5.26325787, -5.73695319],
       [-5.73695319, -5.26325787, -5.73695319, -6.16325787],
       [-6.16325787, -5.73695319, -6.16325787, -6.54695319],
       [-6.54695319, -6.16325787, -6.54695319, -6.89225787]])

In [90]:
for _ in range(100):
    V = greedy_next_V(V)
V

array([[-5.2631579 , -4.73684211, -5.2631579 , -5.73684211],
       [-5.73684211, -5.2631579 , -5.73684211, -6.1631579 ],
       [-6.1631579 , -5.73684211, -6.1631579 , -6.54684211],
       [-6.54684211, -6.1631579 , -6.54684211, -6.8921579 ]])